### ISSUE TITLE
Move plasma configs out of /etc/skel

### ISSUE THREAD

**Issue by llelectronics** [netrunner/netrunner-default-settings#2]
[12:58] <shadeslayer> leszek: you should override XDG_CONFIG_DIR
[12:58] <shadeslayer> similarly, look at other XDG vars for appropriate things

Adding XDG_CONFIG_DIRS=/usr/share/netrunner-default-settings/plasma5-profile/:$XDG_CONFIG_DIRS  /etc/environment and move all plasma5 configs to plasma5-profile. (Test if XDG_CONFIG_DIR also works for other apps so we can move basically every config out of /etc/skel)

**Comment by shadeslayer** [comment]
Actually, I would recommend putting a script in /etc/X11/Xsession.d/ instead of editing /etc/environment
